### ISSUE TITLE
Incorrect window count in training set #2

### ISSUE THREAD

**Issue by popgengent** [AI-sandbox/gnomix#23]
We ran G-Nomix on array data from all autosomes using the default config file for arrays. All chromosomes completed successfully except chromosome 7 which died while training the smoother. The error message was:

>   Traceback (most recent call last):
>   File "gnomix.py", line 396, in <module>
>     model = train_model(config, data_path, verbose=verbose)
>   File "gnomix.py", line 195, in train_model
>     model.train(data=data, retrain_base=retrain_base, evaluate=True, verbose=verbose)
>   File "/tmp/tmp.jstlaojJjT/src/model.py", line 117, in train
>     self.smooth.train(B_t2,y_t2)
>   File "/tmp/tmp.jstlaojJjT/src/Smooth/smooth.py", line 35, in train
>     B_s, y_s = self.process_base_proba(B, y)
>   File "/tmp/tmp.jstlaojJjT/src/Smooth/models.py", line 23, in process_base_proba
>     B_slide, y_slide = slide_window(B, self.S, y)
>   File "/tmp/tmp.jstlaojJjT/src/Smooth/utils.py", line 27, in slide_window
>     y_slide = None if y is None else y.reshape(N*W)
> ValueError: cannot reshape array of size 1609674 into shape (1607992,)

In the final line above, y enters as a 2d object with size 1682*957, but is expected to be reshaped to size N*W=1682*956. We are unsure where the discrepancy in window counts arises, but after changing the value for model: window_size_cM to 0.4 from 0.2 to test if a different window count might work, the program is able to pass the previous point of failure and we confirmed that the new dimensions of y (1682*478) are compatible with the new values of N (1682) and W (478).

**Comment by bchak10** [comment]
Hi all, I've encountered the same problem with a 0.2 window size while training the smoother for certain chromosomes (not all) and would appreciate help with troubleshooting (if possible, without having to increase the window size). Where exactly is this expectation of array dimensions coming from?

Below is the error message—

```
Traceback (most recent call last):
File "[gnomix.py](http://gnomix.py/)", line 397, in <module>
model = train_model(config, data_path, verbose=verbose)
File "[gnomix.py](http://gnomix.py/)", line 195, in train_model
model.train(data=data, retrain_base=retrain_base, evaluate=True, verbose=verbose)
File "/project/lbarreiro/USERS/bridget/programs/gnomix/src/model.py", line 117, in train
self.smooth.train(B_t2,y_t2)
File "/project/lbarreiro/USERS/bridget/programs/gnomix/src/Smooth/smooth.py", line 35, in train
B_s, y_s = self.process_base_proba(B, y)
File "/project/lbarreiro/USERS/bridget/programs/gnomix/src/Smooth/models.py", line 23, in process_base_proba
B_slide, y_slide = slide_window(B, self.S, y)
File "/project/lbarreiro/USERS/bridget/programs/gnomix/src/Smooth/utils.py", line 27, in slide_window
y_slide = None if y is None else y.reshape(N*W)
ValueError: cannot reshape array of size 378148 into shape (377880,)
```
