### ISSUE TITLE
AttributeError: 'LogisticRegressionBase' object has no attribute 'vectorize'

### ISSUE THREAD

**Issue by buyske** [AI-sandbox/gnomix#8]
I'm getting stuck with the error "AttributeError: 'LogisticRegressionBase' object has no attribute 'vectorize'".

Here is my command and the output:

```
gnomix % python gnomix.py ALL.chr22.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz demo/data/allchrs.b37.gmap chr_22 22 False pretrained_gnomix_models/chr22/model_chm_22.pkl

--------------------------------------------------------------------------------
-----------------------------------  Gnomix  -----------------------------------
--------------------------------------------------------------------------------
When using this software, please cite: 
Helgi Hilmarsson, Arvind S Kumar, Richa Rastogi, Carlos D Bustamante, 
Daniel Mas Montserrat, Alexander G Ioannidis: 
"High Resolution Ancestry Deconvolution for Next Generation Genomic Data" 
https://www.biorxiv.org/content/10.1101/2021.09.19.460980v1
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Launching in pre-trained mode...
Loading model...
Launching inference...
Loading and processing query file...
- Number of SNPs from model: 317408
- Number of SNPs from file: 1103547
- Number of intersecting SNPs: 317361
- Percentage of model SNPs covered by query file: 99.99%
- Found 8 (0.0025%) different reference variants. Adjusting...
Inferring ancestry on query data...
Traceback (most recent call last):
  File "gnomix.py", line 372, in <module>
    run_inference(base_args, model, 
  File "gnomix.py", line 53, in run_inference
    B_query = model.base.predict_proba(X_query)
  File "src/Base/base.py", line 136, in predict_proba
    if self.vectorize:
AttributeError: 'LogisticRegressionBase' object has no attribute 'vectorize'
```

And here are the details of my configuration

Macintosh OS 11.6 "Big Sur"
python 3.9.7

matplotlib 3.4.3
numpy 1.21.3
pandas 1.3.4
PyYAML 6.0
scikit-allel 1.3.5
scikit-learn 0.23.2
scipy 1.7.1
seaborn 0.11.2
sklearn 0.0
sklearn-crfsuite 0.3.6
tqdm 4.62.3
uncertainty-calibration 0.0.9
xgboost 1.5.0

Thanks for any help.
Steve

**Comment by buyske** [comment]
I appreciate the quick work, but after pulling the latest version I've graduated to another problem

```
Inferring ancestry on query data...
/usr/local/lib/python3.9/site-packages/sklearn/base.py:209: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  warnings.warn('From version 0.24, get_params will raise an '
Traceback (most recent call last):
  File "gnomix.py", line 383, in <module>
    run_inference(base_args, model, 
  File "gnomix.py", line 55, in run_inference
    y_proba_query = model.smooth.predict_proba(B_query)
  File "src/Smooth/smooth.py", line 46, in predict_proba
    proba = self.model.predict_proba(B_s)
  File "/usr/local/lib/python3.9/site-packages/xgboost/sklearn.py", line 1348, in predict_proba
    class_probs = super().predict(
  File "/usr/local/lib/python3.9/site-packages/xgboost/sklearn.py", line 879, in predict
    if self._can_use_inplace_predict():
  File "/usr/local/lib/python3.9/site-packages/xgboost/sklearn.py", line 813, in _can_use_inplace_predict
    not self.enable_categorical
AttributeError: 'XGBClassifier' object has no attribute 'enable_categorical'
```
